spring.application.name=ejercicio11


spring.datasource.url=${DB_URL:jdbc:postgresql://10.200.11.203:5432/personasdb}
spring.datasource.username=${DB_USER:appuser}
spring.datasource.password=${DB_PASS:appclave2026}

# Pool de conexiones limitado.
spring.datasource.hikari.maximum-pool-size=5


spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
